# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6972305a40748304f9016d3cfdb27dcacd375c5ce637a30744d5d204138e127d1ba46297f235208613e1d6efd37f77dc8a4cd5fc4e0172dcdd625b95bd3768ef

test:
  secret_key_base: f799c61a58b13ad7b816001f8d4eddfa669cef8e636876b43c7fb7f05ca81747220862d4f4273ff6e43de682037d8916ecb5868551eecba3481d3ea276fd0d7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
